---
collections: 
  - awx.awx
  - community.vmware
  - community.windows
  - f5networks.f5_modules
  - netapp.ontap
  - netapp_eseries.santricity
# Disabled due to issue with azure_compute #
  # - community.azure 
  # - chocolatey.chocolatey 
  # - azure.azcollection # Disabled due to issue with azure_compute #
  # - netapp.um_info # Disabled due to issue with azure_compute
  # - netapp.azure # Disabled due to issue with azure_compute
  
# Seems to break things in spectacular fashion 
  # - infinidat.infinibox 
